#!/usr/bin/expect
#########################################################################################
# update.exp
# version:1.1
# update:20181031
#########################################################################################
#set type [lindex $argv 0]
#set action [lindex $argv 1]

spawn git pull

expect "Username" {send "dongfeng\r"}
expect "Password" {send "baicells\r"}

send "quit\n"
expect eof
