#!/bin/bash -

#########################################################################################
# update
# version:6.0
# update:20210805
#########################################################################################
VER_DIR=/usr/lib/eGW/.version
VER_PATH=$1
VER_NAME=$2

function wget_version() {
    [[ ! -d $VER_DIR ]] && mkdir -p $VER_DIR
    cd $VER_DIR && rm -rf *
    wget $VER_PATH -O $VER_NAME
    [[ $? == 1 ]] && exit 10
}

function up_version() {
    tar -zxvf $VER_NAME -C $VER_DIR
    ver=$(find $VER_DIR -maxdepth 1 -type f -name "*.rpm")
    if [[ $ver ]] && $(file $ver | grep "RPM" &>/dev/null);then
        #ver_digest=$(rpm -Kv $ver | awk '/SHA1 digest/{print $5}' | sed 's@(\|)@@g')
        #ver_verify=$(cat version.digest)
        keymd5=$(md5sum pubkey)
        stdmd5="268dbc987f81a2d2f0c86001df8ef200  pubkey"
        #if [[ $ver_digest == $ver_verify ]];then
        if [[ $keymd5 == $stdmd5 ]];then
            rpm --import pubkey
        fi
        if [[ ! $(rpm --checksig $ver | grep "NOT OK") ]];then
            rpm -qa | grep WCG
            [[ $? == 0 ]] && rpm -Uvh $ver --force --allfiles & 
            exit 0
        else
            exit 12
        fi
    else
        exit 11
    fi
}

function ver_update() {
    wget_version
    up_version
}

ver_update
