refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
  file:
    kind: file
    path: "log/collector.log"
    encoder:
      pattern: "{d} - {m}{n}"
root:
  level: warn
  appenders:
    - file
loggers:
  app::backend::db:
    level: info
  app::requests:
    level: info
    appenders:
      - file
    additive: false
